name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Pull remote changes
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git pull https://gabe-vazquez:$HF_TOKEN@huggingface.co/spaces/gabe-vazquez/kokoro-tts main
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://gabe-vazquez:$HF_TOKEN@huggingface.co/spaces/gabe-vazquez/kokoro-tts main
